language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  directories:
    - .pip_download_cache
env:
  matrix:
    - REQUESTS=requests==2.0
    - REQUESTS=-U requests
    - REQUESTS="-e git+git://github.com/kennethreitz/requests.git#egg=requests"
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
matrix:
  allow_failures:
    - env: 'REQUESTS="-e git+git://github.com/kennethreitz/requests.git#egg=requests"'
install:
  - "pip install ${REQUESTS}"
  - make develop
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then make lint; fi
  - py.test . --cov responses --cov-report term-missing
