RAM_RESOURCE_TYPES = [  # List of resource types based on SHAREABLE_RESOURCES
    {
        "resourceType": "rds:Cluster",
        "serviceName": "rds",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "imagebuilder:Component",
        "serviceName": "imagebuilder",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "networkmanager:CoreNetwork",
        "serviceName": "networkmanager",
        "resourceRegionScope": "GLOBAL",
    },
    {
        "resourceType": "resource-groups:Group",
        "serviceName": "resource-groups",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "imagebuilder:Image",
        "serviceName": "imagebuilder",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "imagebuilder:ImageRecipe",
        "serviceName": "imagebuilder",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "license-manager:LicenseConfiguration",
        "serviceName": "license-manager",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "appmesh:Mesh",
        "serviceName": "appmesh",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "ec2:PrefixList",
        "serviceName": "ec2",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "codebuild:Project",
        "serviceName": "codebuild",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "codebuild:ReportGroup",
        "serviceName": "codebuild",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "route53resolver:ResolverRule",
        "serviceName": "route53resolver",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "ec2:Subnet",
        "serviceName": "ec2",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "ec2:TransitGatewayMulticastDomain",
        "serviceName": "ec2",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "glue:Database",
        "serviceName": "glue",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "glue:Table",
        "serviceName": "glue",
        "resourceRegionScope": "REGIONAL",
    },
    {
        "resourceType": "glue:Catalog",
        "serviceName": "glue",
        "resourceRegionScope": "REGIONAL",
    },
]

AWS_MANAGED_PERMISSIONS = [
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionRDSCluster",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionRDSCluster",
        "resourceType": "rds:Cluster",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:16.671000",
        "lastUpdatedTime": "2022-06-30 17:04:16.671000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionImageBuilderComponent",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionImageBuilderComponent",
        "resourceType": "imagebuilder:Component",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:21.977000",
        "lastUpdatedTime": "2022-06-30 17:04:21.977000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionsNetworkManagerCoreNetwork",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionsNetworkManagerCoreNetwork",
        "resourceType": "networkmanager:CoreNetwork",
        "status": "ATTACHABLE",
        "creationTime": "2024-10-23 16:34:51.604000",
        "lastUpdatedTime": "2024-10-23 16:34:51.604000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMTransitGatewayPermissionsNetworkManagerCoreNetwork",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMTransitGatewayPermissionsNetworkManagerCoreNetwork",
        "resourceType": "networkmanager:CoreNetwork",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:03:48.071000",
        "lastUpdatedTime": "2022-06-30 17:03:48.071000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMVPCPermissionsNetworkManagerCoreNetwork",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMVPCPermissionsNetworkManagerCoreNetwork",
        "resourceType": "networkmanager:CoreNetwork",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:03:46.477000",
        "lastUpdatedTime": "2022-06-30 17:03:46.477000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionResourceGroup",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionResourceGroup",
        "resourceType": "resource-groups:Group",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:10.914000",
        "lastUpdatedTime": "2022-06-30 17:04:10.914000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionImageBuilderImage",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionImageBuilderImage",
        "resourceType": "imagebuilder:Image",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:21.201000",
        "lastUpdatedTime": "2022-06-30 17:04:21.201000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionImageBuilderImageRecipe",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionImageBuilderImageRecipe",
        "resourceType": "imagebuilder:ImageRecipe",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:22.832000",
        "lastUpdatedTime": "2022-06-30 17:04:22.832000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionLicenseConfiguration",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionLicenseConfiguration",
        "resourceType": "license-manager:LicenseConfiguration",
        "status": "ATTACHABLE",
        "creationTime": "2024-01-31 16:36:13.664000",
        "lastUpdatedTime": "2024-01-31 16:36:13.664000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionAppMesh",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionAppMesh",
        "resourceType": "appmesh:Mesh",
        "status": "ATTACHABLE",
        "creationTime": "2023-03-28 12:27:55.910000",
        "lastUpdatedTime": "2023-03-28 12:27:55.910000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionPrefixList",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionPrefixList",
        "resourceType": "ec2:PrefixList",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:20.594000",
        "lastUpdatedTime": "2022-06-30 17:04:20.594000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionCodeBuildProject",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionCodeBuildProject",
        "resourceType": "codebuild:Project",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:17.595000",
        "lastUpdatedTime": "2022-06-30 17:04:17.595000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionCodeBuildReportGroup",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionCodeBuildReportGroup",
        "resourceType": "codebuild:ReportGroup",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:17.761000",
        "lastUpdatedTime": "2022-06-30 17:04:17.761000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionResolverRule",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionResolverRule",
        "resourceType": "route53resolver:ResolverRule",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:14.752000",
        "lastUpdatedTime": "2022-06-30 17:04:14.752000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionSubnet",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionSubnet",
        "resourceType": "ec2:Subnet",
        "status": "ATTACHABLE",
        "creationTime": "2024-10-30 15:11:41.358000",
        "lastUpdatedTime": "2024-10-30 15:11:41.358000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionTransitGatewayMulticastDomain",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionTransitGatewayMulticastDomain",
        "resourceType": "ec2:TransitGatewayMulticastDomain",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:13.461000",
        "lastUpdatedTime": "2022-06-30 17:04:13.461000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionGlueDatabase",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionGlueDatabase",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:25.912000",
        "lastUpdatedTime": "2022-06-30 17:04:25.912000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMLFEnabledGlueAllTablesReadWriteForDatabase",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMLFEnabledGlueAllTablesReadWriteForDatabase",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2023-06-27 17:05:24.471000",
        "lastUpdatedTime": "2023-06-27 17:05:24.471000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMLFEnabledGlueDatabaseReadWrite",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMLFEnabledGlueDatabaseReadWrite",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2023-06-27 17:05:27.153000",
        "lastUpdatedTime": "2023-06-27 17:05:27.153000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueAllTablesReadWriteForDatabase",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueAllTablesReadWriteForDatabase",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:19:43.345000",
        "lastUpdatedTime": "2022-10-27 14:19:43.345000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueDatabaseReadWrite",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueDatabaseReadWrite",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:20:08.415000",
        "lastUpdatedTime": "2022-10-27 14:20:08.415000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueTableReadWriteForDatabase",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueTableReadWriteForDatabase",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:19:17.062000",
        "lastUpdatedTime": "2022-10-27 14:19:17.062000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueDatabaseReadWrite",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueDatabaseReadWrite",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:22:14.138000",
        "lastUpdatedTime": "2022-10-27 14:22:14.138000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueTableReadWriteForDatabase",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueTableReadWriteForDatabase",
        "resourceType": "glue:Database",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:21:49.920000",
        "lastUpdatedTime": "2022-10-27 14:21:49.920000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionGlueTable",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionGlueTable",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:24.372000",
        "lastUpdatedTime": "2022-06-30 17:04:24.372000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMLFEnabledGlueDatabaseReadWriteForTable",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMLFEnabledGlueDatabaseReadWriteForTable",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2023-06-27 17:05:33.534000",
        "lastUpdatedTime": "2023-06-27 17:05:33.534000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMLFEnabledGlueTableReadWrite",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMLFEnabledGlueTableReadWrite",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2023-06-27 17:05:21.095000",
        "lastUpdatedTime": "2023-06-27 17:05:21.095000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueDatabaseReadWriteForTable",
        "version": "2",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueDatabaseReadWriteForTable",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:09.034000",
        "lastUpdatedTime": "2022-06-30 17:04:09.034000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueTableReadWrite",
        "version": "2",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueTableReadWrite",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:03.947000",
        "lastUpdatedTime": "2022-06-30 17:04:03.947000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueDatabaseReadWriteForTable",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueDatabaseReadWriteForTable",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:22:26.191000",
        "lastUpdatedTime": "2022-10-27 14:22:26.191000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueTableReadWrite",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueTableReadWrite",
        "resourceType": "glue:Table",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:22:01.908000",
        "lastUpdatedTime": "2022-10-27 14:22:01.908000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMDefaultPermissionGlueCatalog",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMDefaultPermissionGlueCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-06-30 17:04:26.612000",
        "lastUpdatedTime": "2022-06-30 17:04:26.612000",
        "isResourceTypeDefault": True,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueAllTablesReadWriteForCatalog",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueAllTablesReadWriteForCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:19:56.250000",
        "lastUpdatedTime": "2022-10-27 14:19:56.250000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueDatabaseReadWriteForCatalog",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueDatabaseReadWriteForCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:20:20.322000",
        "lastUpdatedTime": "2022-10-27 14:20:20.322000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionGlueTableReadWriteForCatalog",
        "version": "3",
        "defaultVersion": True,
        "name": "AWSRAMPermissionGlueTableReadWriteForCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:19:30.644000",
        "lastUpdatedTime": "2022-10-27 14:19:30.644000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueDatabaseReadWriteForCatalog",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueDatabaseReadWriteForCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:22:37.435000",
        "lastUpdatedTime": "2022-10-27 14:22:37.435000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
    {
        "arn": "arn:aws:ram::aws:permission/AWSRAMPermissionLFTagGlueTableReadWriteForCatalog",
        "version": "1",
        "defaultVersion": True,
        "name": "AWSRAMPermissionLFTagGlueTableReadWriteForCatalog",
        "resourceType": "glue:Catalog",
        "status": "ATTACHABLE",
        "creationTime": "2022-10-27 14:21:37.593000",
        "lastUpdatedTime": "2022-10-27 14:21:37.593000",
        "isResourceTypeDefault": False,
        "permissionType": "AWS_MANAGED",
    },
]
