# Run separate test cases to verify Moto works with older versions of dependencies
#
name: "Outdated Dependency Tests"

on:
  pull_request:
    types: [ labeled ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    if: ${{ github.event.label.name == 'moto-core' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        responses-version: ["0.13.0", "0.15.0", "0.17.0", "0.19.0", "0.20.0" ]
        mock-version: [ "3.0.5", "4.0.0", "4.0.3" ]
        werkzeug-version: ["2.0.1", "2.1.1"]
        openapi-spec-validator-version: ["0.4.0", "0.5.0"]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install project dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install responses==${{ matrix.responses-version }}
        pip install mock==${{ matrix.mock-version }}
        pip install werkzeug==${{ matrix.werkzeug-version }}
        pip install openapi-spec-validator==${{ matrix.openapi-spec-validator-version }}

    - name: Run tests
      run: |
        pytest -sv tests/test_core ./tests/test_apigateway/test_apigateway_integration.py ./tests/test_s3/test_server.py
